# random normal

In [44]:
 np.random.normal(0, 1, 5)

array([ 0.50690734,  0.64121754, -1.72586574,  1.37240847, -0.10254977])

In [43]:
np.random.normal(0, 1, (2,3))

array([[-0.99777178, -0.50040184,  0.50624525],
       [ 1.57747514,  0.62411144,  0.70136554]])

In [46]:
np.random.normal(0, 9, (2,3))

array([[-7.44466405, -9.57623691,  3.08807284],
       [ 1.72881453, -4.5621891 , -3.82618245]])

# zeros

In [19]:
# sifirdan array oluşturma
np.zeros(10, dtype=int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# ones

In [20]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.full((2,4), 3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [22]:
# 0 ile 1 arasında rastgele 10 sayı oluştur
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# 1 boyutlu array

In [23]:
# Başlangıç: NumPy Kurulumu ve Kullanımı
import numpy as np

# Başlangıç: NumPy ile Bir Array Oluşturma
# 1D Array Oluşturma
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d


array([1, 2, 3, 4, 5])

# 2 boyutlu array

In [24]:
# 2D Array Oluşturma
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
# Başlık 1: Array Özellikleri
# Shape, Size, Data Type ve Dimensionality
# shape:  array’in kaç satır ve kaç sütundan oluştuğunu gösterir.
print(f"Array 1D Shape: {arr_1d.shape}")
print(f"Array 2D Shape: {arr_2d.shape}")
print(f"Array 1D Size: {arr_1d.size}")
print(f"Array 2D Size: {arr_2d.size}")
print(f"Array 1D Data Type: {arr_1d.dtype}")
print(f"Array 2D Data Type: {arr_2d.dtype}")
print(f"Array 1D Dimensionality: {arr_1d.ndim}")
print(f"Array 2D Dimensionality: {arr_2d.ndim}")

Array 1D Shape: (5,)
Array 2D Shape: (3, 2)
Array 1D Size: 5
Array 2D Size: 6
Array 1D Data Type: int64
Array 2D Data Type: int64
Array 1D Dimensionality: 1
Array 2D Dimensionality: 2


In [6]:
# Başlık 2: Array Elemanlarına Erişim
# Indexleme 
print(f"Array 1D Eleman 3: {arr_1d[2]}")
print(f"Array 2D 2. Satır, 1. Eleman: {arr_2d[1, 0]}")
print(f"Array 2D 2. Satır: {arr_2d[1]}")


Array 1D Eleman 3: 3
Array 2D 2. Satır, 1. Eleman: 3
Array 2D 2. Satır: [3 4]
Array 1D Dilimleme (1:4): [2 3 4]


# Matematiksel İşlemler

In [7]:
# Başlık 3: Array Matematiksel İşlemleri
# Array ile Matematiksel Operasyonlar
arr_add = arr_1d + 5
arr_sub = arr_1d - 2
arr_mult = arr_1d * 2
arr_div = arr_1d / 2

print(f"Array 1D + 5: {arr_add}")
print(f"Array 1D - 2: {arr_sub}")
print(f"Array 1D * 2: {arr_mult}")
print(f"Array 1D / 2: {arr_div}")

Array 1D + 5: [ 6  7  8  9 10]
Array 1D - 2: [-1  0  1  2  3]
Array 1D * 2: [ 2  4  6  8 10]
Array 1D / 2: [0.5 1.  1.5 2.  2.5]


In [8]:
# Başlık 4: Array'ler ile İstatistiksel Hesaplamalar
# Mean, Sum, Max, Min
mean_value = np.mean(arr_1d)
sum_value = np.sum(arr_1d)
max_value = np.max(arr_1d)
min_value = np.min(arr_1d)

print(f"Array 1D Mean: {mean_value}")
print(f"Array 1D Sum: {sum_value}")
print(f"Array 1D Max: {max_value}")
print(f"Array 1D Min: {min_value}")

Array 1D Mean: 3.0
Array 1D Sum: 15
Array 1D Max: 5
Array 1D Min: 1


# Reshape

In [9]:
# Başlık 5: Array'ler ile İleri Seviye Manipülasyonlar
# Array Şekil Değiştirme
reshaped_array = arr_2d.reshape(2, 3)
print(f"Reshape Array 2D (2,3): \n{reshaped_array}")

# Eleman Ekleyip Çıkarma
arr_append = np.append(arr_1d, 6)
arr_remove = np.delete(arr_1d, 2) #2. indexi siler

print(f"Array 1D Append: {arr_append}")
print(f"Array 1D Remove (index 2): {arr_remove}")

Reshape Array 2D (2,3): 
[[1 2 3]
 [4 5 6]]
Array 1D Append: [1 2 3 4 5 6]
Array 1D Remove (index 2): [1 2 4 5]


# Concatenate

In [25]:
# concatenate ile arrayleri birleştirme
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


In [26]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

z = np.concatenate((x, y), axis=0)
print(z)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
# axis 1 ile 2 boyuttlu arrayleri yan yana birleştirme
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])

z = np.concatenate((x, y), axis=1)
print(z)

[[1 2 5 6]
 [3 4 7 8]]


# Split

In [28]:
# 1D Array - Eşit parçaya bölme (split)
# Bu array 6 elemanlı ve 3 eşit parçaya bölünüyor, her parça 2 eleman içeriyor
a = np.array([1, 2, 3, 4, 5, 6])
parts = np.split(a, 3)
print(parts)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
# 1D Array - Eşit olmayan parçaya bölme (array_split)
# Eleman sayısı tam bölünemezse array_split kullanılır
b = np.array([1, 2, 3, 4, 5])
parts = np.array_split(b, 3)
print(parts)


[array([1, 2]), array([3, 4]), array([5])]


In [30]:
# 2D Array - Satır bazlı bölme (vsplit)
# 4 satırlı 2D array'i 2 eşit parçaya ayırıyoruz (her biri 2 satır içeriyor)
arr2d = np.array([[1, 2],
                  [3, 4],
                  [5, 6],
                  [7, 8]])
parts = np.vsplit(arr2d, 2)
print(parts[0])
print(parts[1])


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [31]:
# 2D Array - Sütun bazlı bölme (hsplit)
# 4 sütunlu 2D array'i yatay olarak 2 parçaya ayırıyoruz (her biri 2 sütun içeriyor)
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

parts = np.hsplit(arr2d, 2)
print(parts[0])
print(parts[1])


[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


# Sort

In [32]:
# 1D Array Sıralama (Küçükten büyüğe)
# np.sort() fonksiyonu array'i sıralar ama orijinal array değişmez
a = np.array([3, 1, 4, 5, 2])
sorted_a = np.sort(a)
print("Sıralı:", sorted_a)
print("Orijinal:", a)


Sıralı: [1 2 3 4 5]
Orijinal: [3 1 4 5 2]


In [37]:
# 2D Array Sıralama (satır veya sütun bazlı)
arr2d = np.array([[3, 4, 2],
                  [6, 7, 1]])

# axis=1 → satır bazlı sıralama (her satır kendi içinde)
sorted_rows = np.sort(arr2d, axis=1)
print("Satır Bazlı Sıralama:\n", sorted_rows)

# axis=0 → sütun bazlı sıralama (her sütun kendi içinde)
sorted_cols = np.sort(arr2d, axis=0)
print("Sütun Bazlı Sıralama:\n", sorted_cols)


Satır Bazlı Sıralama:
 [[2 3 4]
 [1 6 7]]
Sütun Bazlı Sıralama:
 [[3 4 1]
 [6 7 2]]


In [35]:
# Sıralı elemanların orijinal indekslerini bulma: np.argsort()
# Bu fonksiyon, sıralama sonucu oluşacak dizinin indeks sırasını döner
x = np.array([40, 10, 20])
indices = np.argsort(x)
print("Sıralama için indeksler:", indices)

# Bu indekslerle sıralı hali:
print("Sıralı:", x[indices])


Sıralama için indeksler: [1 2 0]
Sıralı: [10 20 40]


# Slicing

In [2]:
import numpy as np

# 1D array tanımla
a = np.array([10, 20, 30, 40, 50])

# İlk 3 elemanı al
print(a[:3])  # [10 20 30]

# 2. indeksten sona kadar
print(a[2:])  # [30 40 50]

# Ortadaki elemanlar (1'den 4'e kadar, 4 dahil değil)
print(a[1:4])  # [20 30 40]

# Son 2 eleman
print(a[-2:])  # [40 50]

# Her 2. elemanı al
print(a[::2])  # [10 30 50]


[10 20 30]
[30 40 50]
[20 30 40]
[40 50]
[10 30 50]


In [3]:
# 2D array tanımla (3 satır, 4 sütun)
b = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

# İlk satırı al
print(b[0])  # [1 2 3 4]

# İlk iki satırı al
print(b[:2])  
# [[1 2 3 4]
#  [5 6 7 8]]

# Tüm satırlar, ilk iki sütun
print(b[:, :2])
# [[ 1  2]
#  [ 5  6]
#  [ 9 10]]

# 2. satırın 1. ve 2. sütunları
print(b[1, 1:3])  # [6 7]

# Son satır
print(b[-1])  # [9 10 11 12]

# Belirli bir alan (alt küme)
print(b[1:3, 2:4])
# [[ 7  8]
#  [11 12]]


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[6 7]
[ 9 10 11 12]
[[ 7  8]
 [11 12]]


# Fancy İndex

In [4]:
# 1D array tanımla
a = np.array([10, 20, 30, 40, 50])

# Belirli indeksleri al (0, 2 ve 4. elemanlar)
print(a[[0, 2, 4]])  # [10 30 50]

# İndeksler array ile de verilebilir
indices = [1, 3] # istediğimiz indexleri kaydedip direkt arraye veriyoruz
print(a[indices])  # [20 40]


[10 30 50]
[20 40]
